# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-12 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('exhibition', '0002_add_path_fields_20170522_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('desc', models.CharField(default=None, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Tagged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_tagged_tagged_items', to='contenttypes.ContentType', verbose_name='Content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_tagged_items', to='exhibition.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='exhibition.Tagged', to='exhibition.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='cg',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='exhibition.Tagged', to='exhibition.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='shortvideo',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='exhibition.Tagged', to='exhibition.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='torrent',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='exhibition.Tagged', to='exhibition.Tag', verbose_name='Tags'),
        ),
    ]
