# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0005_add_anime_episode_length_desc_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='episodes',
            field=models.TextField(default=None, null=True),
        ),
    ]
