# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('exhibition', '0008_change_cg_source_pixiv_id_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedArtists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_taggedartists_tagged_items', to='contenttypes.ContentType', verbose_name='Content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_taggedartists_TaggedArtists', to='exhibition.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaggedCharactors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_taggedcharactors_tagged_items', to='contenttypes.ContentType', verbose_name='Content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_taggedcharactors_TaggedCharactors', to='exhibition.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaggedCopyright',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_taggedcopyright_tagged_items', to='contenttypes.ContentType', verbose_name='Content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_taggedcopyright_TaggedCopyright', to='exhibition.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaggedGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_taggedgeneral_tagged_items', to='contenttypes.ContentType', verbose_name='Content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_taggedgeneral_TaggedGeneral', to='exhibition.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='cg',
            name='tags_string',
        ),
        migrations.AddField(
            model_name='cg',
            name='donmai_uploader_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cg',
            name='fav_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cg',
            name='rating',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='cg',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='anime',
            name='cover_path',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cg',
            name='artist_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='exhibition.TaggedArtists', to='exhibition.Tag', verbose_name=b'artists'),
        ),
        migrations.AddField(
            model_name='cg',
            name='character_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='exhibition.TaggedCharactors', to='exhibition.Tag', verbose_name=b'charactors'),
        ),
        migrations.AddField(
            model_name='cg',
            name='copyright_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='exhibition.TaggedCopyright', to='exhibition.Tag', verbose_name='\u4f5c\u54c1\u7248\u6743'),
        ),
        migrations.AddField(
            model_name='cg',
            name='general_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='exhibition.TaggedGeneral', to='exhibition.Tag', verbose_name='\u4e00\u822c\u6807\u7b7e'),
        ),
    ]
